### ISSUE TITLE
The testimonial should be made in to a carousel

### ISSUE THREAD

**Issue by lindseybateman** [wercker/wercker-corporate#15]
- [x] Styling of the navigation #16
- [x] Adding css animation #17

more todo's welcome @yoshuawuyts 

![testimonial](https://cloud.githubusercontent.com/assets/2393218/5678385/23a7ff38-97f2-11e4-96c7-3f68548574bc.png)

**Comment by yoshuawuyts** [comment]
Added two extra points to the list, lmk what you think @lindseybateman
